In [3]:
#Exercici 3
print('Exercici 3')

import numpy as np

def random_array():
        a=int(input('Introduce el número de filas y columnas #'))            
        array=np.random.randint(0,101,(a,a))
        return array
            
arr=(random_array())
print(arr)

sumac = np.sum(arr,axis=0)
print ('La suma de los valores por columna es',sumac)
sumaf = np.sum(arr,axis=1)
print ('La suma de los valores por fila es',sumaf)

Exercici 3
Introduce el número de filas y columnas #3
[[23 91  4]
 [94 35 45]
 [79 19 56]]
La suma de los valores por columna es [196 145 105]
La suma de los valores por fila es [118 174 154]
