In [12]:
#Exercici 2
print('Exercici 2')

import numpy as np

def random_array():
        a=int(input('Introduce el número de filas y columnas #'))            
        array=np.random.randint(0,101,(a,a))
        print (array)
            
random_array()            
        

Exercici 2
Introduce el número de filas y columnas #7
[[56 37 51 51  5 99 99]
 [99 51 51 88 89 90 94]
 [46 73  9 21 18 66 41]
 [22 70 87  4 74  4  5]
 [ 7  5 61  9 25 77 56]
 [89 91 33 95 62 80 68]
 [30 77 90 65 28 66  1]]
